pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "your-dockerhub-username/ci-cd-nodejs-app"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/your-username/ci-cd-pipeline-nodejs.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$BUILD_NUMBER ./app'
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_HUB_TOKEN')]) {
                    sh "echo $DOCKER_HUB_TOKEN | docker login -u your-dockerhub-username --password-stdin"
                    sh "docker push $DOCKER_IMAGE:$BUILD_NUMBER"
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh "kubectl apply -f k8s/"
            }
        }
    }
}

